#############################################################################
# Makefile for building: demos
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  ../demos.pro
# Template: subdirs
# Command: /usr/lib/arm-linux-gnueabihf/qt5/bin/qmake -o Makefile ../demos.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-paratrooper \
		sub-basketball


sub-paratrooper-qmake_all:  FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile
	cd paratrooper/ && $(MAKE) -f Makefile qmake_all
sub-paratrooper: FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile
sub-paratrooper-make_first: FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-paratrooper-all: FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-paratrooper-clean: FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-paratrooper-distclean: FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-paratrooper-install_subtargets: FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-paratrooper-uninstall_subtargets: FORCE
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-basketball-qmake_all:  FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile
	cd basketball/ && $(MAKE) -f Makefile qmake_all
sub-basketball: FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile
sub-basketball-make_first: FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-basketball-all: FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-basketball-clean: FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-basketball-distclean: FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-basketball-install_subtargets: FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-basketball-uninstall_subtargets: FORCE
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: ../demos.pro /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		../demos.pro
	$(QMAKE) -o Makefile ../demos.pro
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf:
../demos.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ../demos.pro

qmake_all: sub-paratrooper-qmake_all sub-basketball-qmake_all FORCE

make_first: sub-paratrooper-make_first sub-basketball-make_first FORCE
all: sub-paratrooper-all sub-basketball-all FORCE
clean: sub-paratrooper-clean sub-basketball-clean FORCE
distclean: sub-paratrooper-distclean sub-basketball-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-paratrooper-install_subtargets sub-basketball-install_subtargets FORCE
uninstall_subtargets: sub-paratrooper-uninstall_subtargets sub-basketball-uninstall_subtargets FORCE

sub-paratrooper-check:
	@test -d paratrooper/ || mkdir -p paratrooper/
	cd paratrooper/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/paratrooper/paratrooper.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-basketball-check:
	@test -d basketball/ || mkdir -p basketball/
	cd basketball/ && ( test -e Makefile || $(QMAKE) /home/ken/src/Bacon2D/games/basketball/basketball.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-paratrooper-check sub-basketball-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

